spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AWS_RDS_URL_DEV}
    username: ${AWS_RDS_USERNAME_DEV}
    password: ${AWS_RDS_PASSWORD_DEV}

  sql:
    init:
      mode: never
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql


  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 # Lazy Loading 시, N+1 완화

  data:
    redis:
      host: ${AWS_ELASTICACHE_REDIS_HOST_DEV}
      port: ${AWS_ELASTICACHE_REDIS_PORT_DEV}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_DEV}
      secretKey: ${AWS_SECRET_KEY_DEV}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
      path: ${AWS_S3_FILE_DEFAULT_PATH}
    region:
      static: ${AWS_REGION_DEV}
    stack:
      auto: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  secret: ${JWT_SECRET}
